name: Generate Terraform Docs

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0

      - name: Generate README with terraform-docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true