name: Generate Terraform Docs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
permissions:
    contents: write 

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # IMPORTANT: ensures PR branch is checked out (not master)
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform Docs and update README
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: update terraform docs"