name: Generate Terraform Docs

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render terraform docs and push changes
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"